const horses = [
	{
		name: "Lana Melton",
		stable: "Mollis Inc.",
		osnum: "14",
		osnumraceav: "69",
		winperc: "57",
		osplaceperc: "38",
		breedingdate: "2021-06-26 01:11:32",
		bloodline: "vel,",
		boolean: "Mare"
	},
	{
		name: "Murphy Osborne",
		stable: "Tristique Ac Eleifend Consulting",
		osnum: "17",
		osnumraceav: "70",
		winperc: "53",
		osplaceperc: "57",
		breedingdate: "2020-11-04 10:51:12",
		bloodline: "rhoncus.",
		boolean: "Mare"
	},
	{
		name: "Odessa Holt",
		stable: "Mi Pede Company",
		osnum: "7",
		osnumraceav: "11",
		winperc: "55",
		osplaceperc: "15",
		breedingdate: "2021-07-07 12:12:45",
		bloodline: "mus.",
		boolean: "Stallion"
	},
	{
		name: "Gabriel Woods",
		stable: "Netus Et Ltd",
		osnum: "3",
		osnumraceav: "4",
		winperc: "26",
		osplaceperc: "36",
		breedingdate: "2022-06-30 08:51:31",
		bloodline: "ut,",
		boolean: "Mare"
	},
	{
		name: "Stella Lambert",
		stable: "Sapien Cursus In Institute",
		osnum: "8",
		osnumraceav: "100",
		winperc: "30",
		osplaceperc: "39",
		breedingdate: "2020-11-17 12:04:00",
		bloodline: "Phasellus",
		boolean: "Stallion"
	},
    {
		name: "Eugenia Ross",
		stable: "Orci Luctus Et Institute",
		osnum: "14",
		osnumraceav: "82",
		winperc: "13",
		osplaceperc: "10",
		breedingdate: "2021-10-19 13:50:43",
		bloodline: "magna.",
		boolean: "Mare"
	},
	{
		name: "Alfonso Foreman",
		stable: "Dui Cum Consulting",
		osnum: "3",
		osnumraceav: "9",
		winperc: "9",
		osplaceperc: "5",
		breedingdate: "2021-05-15 13:35:02",
		bloodline: "eros",
		boolean: "Stallion"
	},
	{
		name: "Felix Curry",
		stable: "Molestie Corporation",
		osnum: "20",
		osnumraceav: "66",
		winperc: "19",
		osplaceperc: "39",
		breedingdate: "2022-06-06 10:46:06",
		bloodline: "vehicula",
		boolean: "Mare"
	},
	{
		name: "Amos Hooper",
		stable: "Sem Egestas Ltd",
		osnum: "3",
		osnumraceav: "99",
		winperc: "16",
		osplaceperc: "6",
		breedingdate: "2021-01-21 08:03:49",
		bloodline: "inceptos",
		boolean: "Mare"
	},
	{
		name: "Jamalia Tucker",
		stable: "Molestie In Corp.",
		osnum: "14",
		osnumraceav: "58",
		winperc: "47",
		osplaceperc: "25",
		breedingdate: "2021-08-21 02:57:33",
		bloodline: "Mauris",
		boolean: "Stallion"
	},
    {
		name: "Destiny Richmond",
		stable: "Enim Inc.",
		osnum: "14",
		osnumraceav: "73",
		winperc: "14",
		osplaceperc: "46",
		breedingdate: "2021-11-29 11:12:50",
		bloodline: "aliquet",
		boolean: "Mare"
	},
	{
		name: "Sean Mcfadden",
		stable: "Semper Et Incorporated",
		osnum: "2",
		osnumraceav: "30",
		winperc: "34",
		osplaceperc: "25",
		breedingdate: "2020-11-10 18:21:26",
		bloodline: "dictum",
		boolean: "Mare"
	},
	{
		name: "Orli Dorsey",
		stable: "Urna Justo Corporation",
		osnum: "13",
		osnumraceav: "44",
		winperc: "25",
		osplaceperc: "18",
		breedingdate: "2021-07-07 12:34:31",
		bloodline: "dui",
		boolean: "Stallion"
	},
	{
		name: "Meredith Lindsey",
		stable: "Semper Auctor Foundation",
		osnum: "17",
		osnumraceav: "38",
		winperc: "52",
		osplaceperc: "12",
		breedingdate: "2021-12-08 02:00:08",
		bloodline: "magna",
		boolean: "Mare"
	},
	{
		name: "Gavin Gardner",
		stable: "Duis Mi Corporation",
		osnum: "12",
		osnumraceav: "74",
		winperc: "58",
		osplaceperc: "15",
		breedingdate: "2022-06-24 11:10:22",
		bloodline: "iaculis",
		boolean: "Stallion"
	},
    {
		name: "Jemima Robles",
		stable: "Risus Donec LLP",
		osnum: "11",
		osnumraceav: "91",
		winperc: "14",
		osplaceperc: "33",
		breedingdate: "2022-03-27 01:43:07",
		bloodline: "quis",
		boolean: "Mare"
	},
	{
		name: "Patience Barber",
		stable: "In LLC",
		osnum: "16",
		osnumraceav: "43",
		winperc: "30",
		osplaceperc: "19",
		breedingdate: "2022-09-10 21:13:30",
		bloodline: "lobortis",
		boolean: "Mare"
	},
	{
		name: "Mariko Barr",
		stable: "Integer Sem Incorporated",
		osnum: "10",
		osnumraceav: "89",
		winperc: "51",
		osplaceperc: "53",
		breedingdate: "2021-09-01 12:07:48",
		bloodline: "id",
		boolean: "Stallion"
	},
	{
		name: "Troy Oliver",
		stable: "Malesuada Associates",
		osnum: "5",
		osnumraceav: "11",
		winperc: "18",
		osplaceperc: "43",
		breedingdate: "2021-08-27 09:12:36",
		bloodline: "vulputate,",
		boolean: "Mare"
	},
	{
		name: "Calvin Rosario",
		stable: "Tincidunt Aliquam Limited",
		osnum: "10",
		osnumraceav: "98",
		winperc: "14",
		osplaceperc: "59",
		breedingdate: "2022-08-20 23:01:00",
		bloodline: "non",
		boolean: "Stallion"
	},
    {
		name: "Lyle Santos",
		stable: "Blandit Corp.",
		osnum: "15",
		osnumraceav: "82",
		winperc: "14",
		osplaceperc: "28",
		breedingdate: "2021-06-26 21:36:45",
		bloodline: "nec",
		boolean: "Mare"
	},
	{
		name: "Kennedy Jensen",
		stable: "Nunc Id Company",
		osnum: "7",
		osnumraceav: "13",
		winperc: "29",
		osplaceperc: "59",
		breedingdate: "2021-10-24 18:31:44",
		bloodline: "feugiat",
		boolean: "Mare"
	},
	{
		name: "Amena Puckett",
		stable: "Nec Ante Blandit Corporation",
		osnum: "11",
		osnumraceav: "12",
		winperc: "51",
		osplaceperc: "56",
		breedingdate: "2020-10-12 03:48:53",
		bloodline: "cursus",
		boolean: "Mare"
	},
	{
		name: "Colton Roberson",
		stable: "Scelerisque LLC",
		osnum: "8",
		osnumraceav: "86",
		winperc: "35",
		osplaceperc: "52",
		breedingdate: "2020-11-19 13:53:28",
		bloodline: "natoque",
		boolean: "Stallion"
	},
	{
		name: "Angela Franco",
		stable: "Molestie Tellus Incorporated",
		osnum: "12",
		osnumraceav: "54",
		winperc: "42",
		osplaceperc: "45",
		breedingdate: "2022-02-20 02:08:31",
		bloodline: "fringilla,",
		boolean: "Mare"
	},
    {
		name: "Ulysses O'connor",
		stable: "Pellentesque A Institute",
		osnum: "10",
		osnumraceav: "21",
		winperc: "52",
		osplaceperc: "57",
		breedingdate: "2020-10-30 18:19:07",
		bloodline: "parturient",
		boolean: "Stallion"
	},
	{
		name: "Macaulay Stanton",
		stable: "Tempus Lorem Associates",
		osnum: "4",
		osnumraceav: "96",
		winperc: "24",
		osplaceperc: "12",
		breedingdate: "2022-07-12 21:03:22",
		bloodline: "volutpat.",
		boolean: "Mare"
	},
	{
		name: "Dorothy Bruce",
		stable: "A Malesuada Inc.",
		osnum: "8",
		osnumraceav: "81",
		winperc: "18",
		osplaceperc: "30",
		breedingdate: "2022-01-11 19:47:42",
		bloodline: "dolor,",
		boolean: "Mare"
	},
	{
		name: "Claire Cole",
		stable: "Sodales Industries",
		osnum: "10",
		osnumraceav: "46",
		winperc: "36",
		osplaceperc: "33",
		breedingdate: "2020-11-23 14:09:59",
		bloodline: "Donec",
		boolean: "Mare"
	},
	{
		name: "Patience Hooper",
		stable: "Ac Risus Morbi LLC",
		osnum: "1",
		osnumraceav: "89",
		winperc: "21",
		osplaceperc: "33",
		breedingdate: "2022-07-20 04:33:29",
		bloodline: "Proin",
		boolean: "Mare"
	}
];
